version: '3'
services:

  docker-fresh-redis:
    # command: redis-server --appendonly yes
    container_name: docker-fresh-redis
    image: redis:3.2.10-alpine
    ports:
     - 6379:6379

networks:
  default:
    external:
      name: environment_docker-fresh
